---
- hosts: game
  roles:
    - { role: guest/network, become: yes, tags: not_for_vagrant, base }
    - { role: common/base, become: yes, tags: base }
    - { role: guest/game, become: yes }
    - { role: guest/checker, become: yes }
